#
# Automagically generated by Approximatrix Simply Fortran 3.3
#
FC="C:\Program Files (x86)\Simply Fortran 3\mingw-w64\bin\gfortran.exe"
CC="C:\Program Files (x86)\Simply Fortran 3\mingw-w64\bin\gcc.exe"
AR="C:\Program Files (x86)\Simply Fortran 3\mingw-w64\bin\ar.exe"
WRC="C:\Program Files (x86)\Simply Fortran 3\mingw-w64\bin\windres.exe"
PRJTK="C:\Program Files (x86)\Simply Fortran 3\fwin\sfprjtk.exe"
RM=rm -f

IDIR=

LDIR=


OPTFLAGS= -g

SPECIALFLAGS=$(IDIR)

RCFLAGS=-O coff

PRJ_FFLAGS=

PRJ_CFLAGS=

PRJ_LFLAGS=

FFLAGS=$(SPECIALFLAGS) $(OPTFLAGS) $(PRJ_FFLAGS) -Jmodules 

CFLAGS=$(SPECIALFLAGS) $(OPTFLAGS) $(PRJ_CFLAGS)

"build\ANMseries.o": ".\ANMseries.f" ".\donnees.inc" ".\maillage.inc"
	@echo Compiling .\ANMseries.f
	@$(FC) -c -o "build\ANMseries.o" $(FFLAGS) ".\ANMseries.f"

"build\assemb.o": ".\assemb.f" ".\maillage.inc"
	@echo Compiling .\assemb.f
	@$(FC) -c -o "build\assemb.o" $(FFLAGS) ".\assemb.f"

"build\basis.o": ".\basis.f"
	@echo Compiling .\basis.f
	@$(FC) -c -o "build\basis.o" $(FFLAGS) ".\basis.f"
"modules\basis.mod" : "build\basis.o" .EXISTSONLY
	@echo Compiling .\basis.f
	@$(FC) -c -o "build\basis.o" $(FFLAGS) ".\basis.f"

"build\CG.o": ".\CG.f"
	@echo Compiling .\CG.f
	@$(FC) -c -o "build\CG.o" $(FFLAGS) ".\CG.f"

"build\Chol.o": ".\Chol.f" "modules\basis.mod"
	@echo Compiling .\Chol.f
	@$(FC) -c -o "build\Chol.o" $(FFLAGS) ".\Chol.f"
"modules\lu.mod" : "build\Chol.o" .EXISTSONLY
	@echo Compiling .\Chol.f
	@$(FC) -c -o "build\Chol.o" $(FFLAGS) ".\Chol.f"

"build\condlim.o": ".\condlim.f"
	@echo Compiling .\condlim.f
	@$(FC) -c -o "build\condlim.o" $(FFLAGS) ".\condlim.f"

"build\deform.o": ".\deform.f" ".\donnees.inc" ".\maillage.inc"
	@echo Compiling .\deform.f
	@$(FC) -c -o "build\deform.o" $(FFLAGS) ".\deform.f"

"build\elem_2D.o": ".\elem_2D.f"
	@echo Compiling .\elem_2D.f
	@$(FC) -c -o "build\elem_2D.o" $(FFLAGS) ".\elem_2D.f"

"build\Fnl.o": ".\Fnl.f" ".\maillage.inc" ".\donnees.inc"
	@echo Compiling .\Fnl.f
	@$(FC) -c -o "build\Fnl.o" $(FFLAGS) ".\Fnl.f"

"build\force.o": ".\force.f" ".\donnees.inc" ".\maillage.inc"
	@echo Compiling .\force.f
	@$(FC) -c -o "build\force.o" $(FFLAGS) ".\force.f"

"build\increm.o": ".\increm.f" ".\donnees.inc" ".\maillage.inc" ".\varstok.inc"
	@echo Compiling .\increm.f
	@$(FC) -c -o "build\increm.o" $(FFLAGS) ".\increm.f"

"build\main.o": ".\main.f" ".\donnees.inc"
	@echo Compiling .\main.f
	@$(FC) -c -o "build\main.o" $(FFLAGS) ".\main.f"

"build\math.o": ".\math.f"
	@echo Compiling .\math.f
	@$(FC) -c -o "build\math.o" $(FFLAGS) ".\math.f"

"build\Rayon.o": ".\Rayon.f"
	@echo Compiling .\Rayon.f
	@$(FC) -c -o "build\Rayon.o" $(FFLAGS) ".\Rayon.f"

"build\rigidite.o": ".\rigidite.f" ".\maillage.inc" ".\donnees.inc"
	@echo Compiling .\rigidite.f
	@$(FC) -c -o "build\rigidite.o" $(FFLAGS) ".\rigidite.f"

"build\uti.o": ".\uti.f" ".\donnees.inc" ".\maillage.inc"
	@echo Compiling .\uti.f
	@$(FC) -c -o "build\uti.o" $(FFLAGS) ".\uti.f"

clean: .SYMBOLIC
	@echo Deleting build\ANMseries.o and related files
	@$(RM) "build\ANMseries.o"
	@echo Deleting build\assemb.o and related files
	@$(RM) "build\assemb.o"
	@echo Deleting build\basis.o and related files
	@$(RM) "build\basis.o" "modules\basis.mod" "modules\basis.smod"
	@echo Deleting build\CG.o and related files
	@$(RM) "build\CG.o"
	@echo Deleting build\Chol.o and related files
	@$(RM) "build\Chol.o" "modules\lu.mod" "modules\lu.smod"
	@echo Deleting build\condlim.o and related files
	@$(RM) "build\condlim.o"
	@echo Deleting build\deform.o and related files
	@$(RM) "build\deform.o"
	@echo Deleting build\elem_2D.o and related files
	@$(RM) "build\elem_2D.o"
	@echo Deleting build\Fnl.o and related files
	@$(RM) "build\Fnl.o"
	@echo Deleting build\force.o and related files
	@$(RM) "build\force.o"
	@echo Deleting build\increm.o and related files
	@$(RM) "build\increm.o"
	@echo Deleting build\main.o and related files
	@$(RM) "build\main.o"
	@echo Deleting build\math.o and related files
	@$(RM) "build\math.o"
	@echo Deleting build\Rayon.o and related files
	@$(RM) "build\Rayon.o"
	@echo Deleting build\rigidite.o and related files
	@$(RM) "build\rigidite.o"
	@echo Deleting build\uti.o and related files
	@$(RM) "build\uti.o"
	@echo Deleting MAN.exe
	@$(RM) "MAN.exe"

"MAN.exe":  "build\ANMseries.o" "build\assemb.o" "build\basis.o" "build\CG.o" "build\Chol.o" "build\condlim.o" "build\deform.o" "build\elem_2D.o" "build\Fnl.o" "build\force.o" "build\increm.o" "build\main.o" "build\math.o" "build\Rayon.o" "build\rigidite.o" "build\uti.o" "build\src-NxH.prj.target"
	@echo Generating MAN.exe
	@$(FC) -o "MAN.exe" -static "build\ANMseries.o" "build\assemb.o" "build\basis.o" "build\CG.o" "build\Chol.o" "build\condlim.o" "build\deform.o" "build\elem_2D.o" "build\Fnl.o" "build\force.o" "build\increm.o" "build\main.o" "build\math.o" "build\Rayon.o" "build\rigidite.o" "build\uti.o" $(LDIR) $(PRJ_LFLAGS)

all: "MAN.exe" .SYMBOLIC

